version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      POSTGRES_USER: test
    ports:
      - "5432:5432"